version: "3.2"

services:
  apache:
    build: './apache/'
    depends_on:
      # - php
      - mysql
    networks:
      # - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/
      # - ./public_html/:/usr/local/apache2/htdocs/
      - ./settings/:/etc/apache2/sites-available/
      # - ./my-httpd.conf:/usr/local/apache2/conf-available/httpd.conf
    extra_hosts:
      - "test.pla:127.0.0.1"
      - "test.local:127.0.0.1"
      - "local.venusinjewels:127.0.0.1"
  mysql:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8091:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - backend
networks:
  frontend:
  backend: